on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  buildmavenDepTree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: demo
        run: mvn --batch-mode --update-snapshots package
      - name: Generate dependency tree
        working-directory: demo
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt -DoutputType=text
      - name: Upload Dependency Tree Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mavendeptree
          path: demo/maven_dep_tree.txt
  semgrep:
    needs: buildmavenDepTree
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: mavendeptree
      - run: cd demo && semgrep ci --supply-chain
